server:
  port: 8085
  max-http-header-size: 256KB
spring:
  profiles:
    active: local
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true

# Optionnel : logs pour voir le routage en action
logging:
  level:
    org.springframework.cloud.gateway: TRACE