@gateway = http://localhost:8085

### =========================================
### 1. USER SERVICE
### =========================================

### Inscription d'un utilisateur
POST {{gateway}}/api/v1/users/register
Content-Type: application/json

{
  "email": "test1@safetag.fr",
  "password": "password123"
}

### Connexion d'un utilisateur
POST {{gateway}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "test1@safetag.fr",
  "password": "password123"
}

### Récupérer un utilisateur par ID
GET {{gateway}}/api/v1/users/5e368863-82d7-4e87-a753-dc2c18730be2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjODcyNzgyOC02ZjM4LTRlZmUtODM0Yy0xMzYzZjc0ZTA3MGUiLCJyb2xlcyI6IlVTRVIiLCJlbWFpbCI6InRlc3Q0QHNhZmV0YWcuY29tIiwiaWF0IjoxNzkwMjU5MDY2LCJleHAiOjE3OTAyNjI2NjZ9.PkYWSIwAGjtRab8nk-Ydyo-e0XNDubuNqv2Ee8fV00A

### =========================================
### 2. RPPS SERVICE
### =========================================

### Rechercher des praticiens (par nom et ville)
GET {{gateway}}/api/v1/rpps/search?name=Dupont&size=10

### Rechercher des praticiens (par géolocalisation)
GET {{gateway}}/api/v1/rpps/search?lat=48.8566&lon=2.3522&radiusKm=10&page=0&size=10

### Consulter un praticien par RPPS
GET {{gateway}}/api/v1/rpps/10000702497

### =========================================
### 3. REVIEW SERVICE
### =========================================

### Créer un avis
POST {{gateway}}/api/v1/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjODcyNzgyOC02ZjM4LTRlZmUtODM0Yy0xMzYzZjc0ZTA3MGUiLCJyb2xlcyI6IlVTRVIiLCJlbWFpbCI6InRlc3Q0QHNhZmV0YWcuY29tIiwiaWF0IjoxNzkwMjU5MDY2LCJleHAiOjE3OTAyNjI2NjZ9.PkYWSIwAGjtRab8nk-Ydyo-e0XNDubuNqv2Ee8fV00A
X-User-Id: 63a8dc0a-5db5-44a1-baa5-48f887feaa55

{
  "rppsId": "10000702497",
  "addressIds": ["123e4567-e89b-12d3-a456-426614174001"],
  "comment": "un très bon médecin docteur!",
  "tags": [
    {
      "category": "HANDICAP",
      "vote": "NEGATIVE"
    },
    {
      "category": "GENRE",
      "vote": "NEUTRAL"
    }
  ],
  "pathologies": ["ANXIETY"]
}

### Créer un avis avec gros mots
POST {{gateway}}/api/v1/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjODcyNzgyOC02ZjM4LTRlZmUtODM0Yy0xMzYzZjc0ZTA3MGUiLCJyb2xlcyI6IlVTRVIiLCJlbWFpbCI6InRlc3Q0QHNhZmV0YWcuY29tIiwiaWF0IjoxNzkwMjU5MDY2LCJleHAiOjE3OTAyNjI2NjZ9.PkYWSIwAGjtRab8nk-Ydyo-e0XNDubuNqv2Ee8fV00A
X-User-Id: 63a8dc0a-5db5-44a1-baa5-48f887feaa55

{
  "rppsId": "12345678890",
  "userId": "c8727828-6f38-4efe-834c-1363f74e070e",
  "addressIds": ["123e4567-e89b-12d3-a456-426614174001"],
  "comment": "bof, un con je vous jure",
  "tags": [
    {
      "category": "HANDICAP",
      "vote": "NEGATIVE"
    },
    {
      "category": "GENRE",
      "vote": "NEUTRAL"
    }
  ]
}