@gateway = http://localhost:8085
### =========================================
### 1. USER SERVICE
### =========================================

### Inscription d'un utilisateur
POST {{gateway}}/api/v1/users/register
Content-Type: application/json

{
  "email": "test1@safetag.fr",
  "password": "password123"
}

### Connexion d'un utilisateur
POST {{gateway}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "test1@safetag.fr",
  "password": "password123"
}

###

### Récupérer un utilisateur par ID
GET {{gateway}}/api/v1/users/5e368863-82d7-4e87-a753-dc2c18730be2

### =========================================
### 3. RPPS SERVICE
### =========================================

### 3.1 Rechercher des praticiens (Exemple : par nom et ville)
GET {{gateway}}/api/v1/practitioners/search?name=Dupont&size=10

### 3.2 Rechercher des praticiens (Exemple : par géolocalisation)
GET {{gateway}}/api/v1/practitioners/search?lat=48.8566&lon=2.3522&radiusKm=10&page=0&size=10

###

### 3.3 Consulter un praticien par RPPS (et déclencher la MAJ opportuniste)
GET {{gateway}}/api/v1/practitioners/10000702497


### =========================================
### 3. REVIEW SERVICE
### =========================================

### Créer un avis
POST {{gateway}}/api/v1/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2M2E4ZGMwYS01ZGI1LTQ0YTEtYmFhNS00OGY4ODdmZWFhNTUiLCJlbWFpbCI6InRlc3QxQHNhZmV0YWcuZnIiLCJpYXQiOjE3NzczODk3MjgsImV4cCI6MTc3NzQ3NjEyOH0.PBk_BxN52pN7ObYfgHXUSwTR5w6AOVmJWFLRv8Qy6eX3W9Q4IVtGO7ykHZQRgks7RIUTgfWQ29X6NMksGwsRFg

{
  "rppsId": "10000702497",
  "userId": "63a8dc0a-5db5-44a1-baa5-48f887feaa55",
  "addressIds": ["123e4567-e89b-12d3-a456-426614174001"],
  "comment": "un très bon médecin docteur!",
  "tags": [
    {
      "category": "HANDICAP",
      "vote": "NEGATIVE"
    },
    {
      "category": "GENRE",
      "vote": "NEUTRAL"
    }
  ],
  "pathologies": ["ANXIETY"]
}
### Créer un avis with bad words
POST {{gateway}}/api/v1/reviews
Content-Type: application/json

{
  "rppsId": "12345678899",
  "userId": "123e4567-e89b-12d3-a456-426614174000",
  "addressIds": ["123e4567-e89b-12d3-a456-426614174001"],
  "comment": "bof, un con je vous jure",
  "tags": [
    {
      "category": "HANDICAP",
      "vote": "NEGATIVE"
    },
    {
      "category": "GENRE",
      "vote": "NEUTRAL"
    }
  ],
  "pathologies": ["ANXIETY"]
}

